
#define NOT_EXPECT_VALUE -1
#define PARAM_ERROR      -2
#define MALLOC_FAILED    -3
#define OPEN_FILE_FAILED -4
#define FILE_NOT_EXISTS  -5
#define PARAM_IS_TOO_SHORT -6
#define GET_CONFIG_VALUE_FAILED -7
